import argparse
import subprocess
import sys
from pathlib import Path

# run_pipeline.py 放在 video_processing_new/ 裡面
SCRIPT_DIR = Path(__file__).resolve().parent

# 專案根目錄應該是 video_processing_new 的上一層：
# D:/資工專題/project/
PROJECT_ROOT = SCRIPT_DIR.parent if SCRIPT_DIR.name == "video_processing" else SCRIPT_DIR

# 統一所有 dataset 都放在 project/dataset，而不是 video_processing_new/dataset
DATASET_DIR = PROJECT_ROOT / "dataset"
DEFAULT_STROKE_CHECKPOINT = PROJECT_ROOT / "models" / "best_model.pt"


def resolve_video_path(video_path_str: str) -> Path:
    """讓 raw_videos/testVid.mp4、絕對路徑、從不同 cwd 執行都能正常解析。"""
    p = Path(video_path_str)

    if p.is_absolute():
        return p

    candidates = [
        Path.cwd() / p,
        PROJECT_ROOT / p,
        SCRIPT_DIR / p,
    ]

    for c in candidates:
        if c.exists():
            return c.resolve()

    return (PROJECT_ROOT / p).resolve()


def resolve_project_path(path_str: str) -> Path:
    """checkpoint 等專案內路徑，預設以 project root 為基準，而不是 video_processing_new。"""
    p = Path(path_str)
    if p.is_absolute():
        return p
    return (PROJECT_ROOT / p).resolve()


def run_step(script_name: str, video_path: Path, extra_args=None) -> None:
    extra_args = extra_args or []
    script_path = SCRIPT_DIR / script_name

    if not script_path.exists():
        raise FileNotFoundError(f"Script not found: {script_path}")

    cmd = [sys.executable, str(script_path), str(video_path), *map(str, extra_args)]

    print(f"\n=== Running {script_name} ===")
    print("[CMD] " + " ".join(cmd))

    # 重點：cwd 一定要設成 PROJECT_ROOT
    # 這樣所有子程式裡的 Path('dataset') 才會指到 project/dataset
    subprocess.run(cmd, check=True, cwd=str(PROJECT_ROOT))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run the full tennis analysis pipeline from one video path."
    )
    parser.add_argument("video_path", type=str, help="例如 raw_videos/testVid.mp4")
    parser.add_argument("--tracknet", action="store_true", help="使用 TrackNet 取代傳統 CV 球追蹤")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=str(DEFAULT_STROKE_CHECKPOINT),
        help="stroke classifier checkpoint；預設 project/dataset/tennis_actions/outputs/croped/best_model.pt",
    )
    parser.add_argument(
        "--target-side",
        type=str,
        default="near",
        choices=["near", "far", "all"],
        help="只對哪一側的擊球 event 做正反拍投票；預設 near。",
    )
    parser.add_argument("--skip-vote", action="store_true", help="跳過正反拍投票 vote_action.py")
    parser.add_argument("--skip-analysis", action="store_true", help="跳過 analysis_per.py")
    parser.add_argument("--skip-visualization", action="store_true", help="跳過 visualization.py")
    parser.add_argument("--debug-bounce", action="store_true", help="傳 --debug 給 bounce.py，輸出較多偵測 debug 圖")
    args = parser.parse_args()

    video_path = resolve_video_path(args.video_path)
    video_name = video_path.stem
    output_base = DATASET_DIR / video_name
    bounce_dir = output_base / "bounce_detector"
    checkpoint = resolve_project_path(args.checkpoint)

    print(f"[INFO] script dir    = {SCRIPT_DIR}")
    print(f"[INFO] project root  = {PROJECT_ROOT}")
    print(f"[INFO] using Python  = {sys.executable}")
    print(f"[INFO] video         = {video_path}")
    print(f"[INFO] output base   = {output_base}")
    print(f"[INFO] bounce dir    = {bounce_dir}")
    print(f"[INFO] checkpoint    = {checkpoint}")

    # 1. Extract frames, auto-detect court ROI, and build valid_mask.png.
    run_step("preprocessing.py", video_path)

    # 2. Detect bounce events and hit intervals.
    bounce_args = ["--debug"] if args.debug_bounce else []
    if args.tracknet:
        tracknet_model_path = PROJECT_ROOT / "models" / "TrackNet.pt"
        if not tracknet_model_path.exists():
            raise FileNotFoundError(f"TrackNet model not found at {tracknet_model_path}")
        bounce_args.extend(["--tracknet-model", str(tracknet_model_path), "--tracknet-only"])
        
    run_step("bounce.py", video_path, bounce_args)

    # 3. Stroke vote. Use YOLO / tracker cache generated by bounce.py.
    if not args.skip_vote:
        if not checkpoint.exists():
            raise FileNotFoundError(
                f"Stroke checkpoint not found: {checkpoint}\n"
                "請用 --checkpoint 指到你的 best_model.pt。"
            )
        run_step(
            "vote_action.py",
            video_path,
            [
                "--checkpoint", checkpoint,
                "--yolo-cache-dir", bounce_dir,
                "--target-side", args.target_side,
            ],
        )

    # 4. Generate bounce/hit analysis CSV and PDF.
    if not args.skip_analysis:
        run_step("analysis_per.py", video_path)

    # 5. Generate overlay video.
    if not args.skip_visualization:
        run_step("visualization.py", video_path)

    print("\n[DONE] Full pipeline completed.")


if __name__ == "__main__":
    main()