import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import pandas as pd
from tqdm import tqdm

# ============================================================
# Clean bounce landing visualization
# ------------------------------------------------------------
# Default sync source is dataset/<video>/frames, because bounce.py also
# detects bounce_events.csv from those extracted frames.
#
# This script intentionally does NOT use:
#   - tracked_path.csv
#   - PlayerDetector / TwoPlayerTracker
#   - ball/player overlays on the original video
#   - hit interval CSV
#
# It uses only:
#   - dataset/<video>/bounce_detector/bounce_events.csv
#   - dataset/<video>/roi_config.json  (only for H projection)
# ============================================================

COURT_WIDTH = 10.97
SINGLES_WIDTH = 8.23
COURT_LENGTH = 23.77
SERVICE_FROM_NET = 6.40
NET_Y = COURT_LENGTH / 2.0
SINGLE_MARGIN = (COURT_WIDTH - SINGLES_WIDTH) / 2.0


def set_video_path(video_path: Path):
    global VIDEO_PATH, video_name, BASE, FRAMES_DIR, ROI_JSON, BOUNCE_DIR
    global BOUNCE_EVENTS_CSV, OUT_PATH_OVERLAY

    VIDEO_PATH = Path(video_path)
    video_name = VIDEO_PATH.stem
    BASE = Path("dataset") / video_name
    FRAMES_DIR = BASE / "frames"
    ROI_JSON = BASE / "roi_config.json"
    BOUNCE_DIR = BASE / "bounce_detector"
    BOUNCE_EVENTS_CSV = BOUNCE_DIR / "bounce_events.csv"
    OUT_PATH_OVERLAY = BOUNCE_DIR / "overlay_bounce_landings.mp4"


def _pick_first_existing_column(df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    for col in candidates:
        if col in df.columns:
            return col
    return None


def load_bounce_events(path: Path, coord_scale: float = 1.0) -> pd.DataFrame:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"bounce_events.csv not found: {path}")

    raw = pd.read_csv(path)
    if raw.empty:
        return pd.DataFrame(columns=["frame_idx", "x", "y", "court_side", "score"])

    frame_col = _pick_first_existing_column(raw, ["peak_frame", "refined_frame", "frame_idx"])
    x_col = _pick_first_existing_column(raw, ["cx", "refined_cx", "x"])
    y_col = _pick_first_existing_column(raw, ["cy", "refined_cy", "y"])
    side_col = _pick_first_existing_column(raw, ["court_side", "landing_side", "side"])
    score_col = _pick_first_existing_column(raw, ["peak_score", "refine_score", "score"])

    if frame_col is None or x_col is None or y_col is None:
        raise ValueError(
            "bounce_events.csv must contain frame/x/y columns, e.g. peak_frame, cx, cy."
        )

    out = pd.DataFrame()
    out["frame_idx"] = pd.to_numeric(raw[frame_col], errors="coerce")
    out["x"] = pd.to_numeric(raw[x_col], errors="coerce") * float(coord_scale)
    out["y"] = pd.to_numeric(raw[y_col], errors="coerce") * float(coord_scale)
    out["court_side"] = raw[side_col].astype(str).str.lower() if side_col else "unknown"
    out["score"] = pd.to_numeric(raw[score_col], errors="coerce") if score_col else np.nan

    out = out.dropna(subset=["frame_idx", "x", "y"]).copy()
    out["frame_idx"] = out["frame_idx"].round().astype(int)
    out["x"] = out["x"].astype(float)
    out["y"] = out["y"].astype(float)
    out = out.sort_values("frame_idx").reset_index(drop=True)
    out["landing_no"] = np.arange(1, len(out) + 1)
    return out


def load_homography_from_roi(roi_json: Path) -> np.ndarray:
    roi_json = Path(roi_json)
    if not roi_json.exists():
        raise FileNotFoundError(f"roi_config.json not found: {roi_json}")

    with open(roi_json, "r", encoding="utf-8") as f:
        data = json.load(f)

    if "H" not in data:
        raise KeyError(
            f"{roi_json} does not contain H. The side-court projection needs the "
            "homography generated by court_detector.py."
        )

    H = np.asarray(data["H"], dtype=np.float64)
    if H.shape != (3, 3):
        raise ValueError(f"Invalid H shape in {roi_json}: {H.shape}")
    return H


def image_to_court_xy(x: float, y: float, H_court_to_image: np.ndarray) -> Optional[Tuple[float, float]]:
    """Project image pixel coordinate to court-meter coordinate.

    court_detector.py stores H as court-model coordinates -> image pixels,
    so image -> court uses inv(H).
    """
    try:
        H_inv = np.linalg.inv(np.asarray(H_court_to_image, dtype=np.float64))
        pts = np.array([[[float(x), float(y)]]], dtype=np.float32)
        out = cv2.perspectiveTransform(pts, H_inv.astype(np.float64)).reshape(-1, 2)[0]
        X, Y = float(out[0]), float(out[1])
    except Exception:
        return None

    if not np.isfinite(X) or not np.isfinite(Y):
        return None
    return X, Y


def is_in_bounds(X: float, Y: float, singles: bool = True, tol: float = 0.03) -> bool:
    width = SINGLES_WIDTH if singles else COURT_WIDTH
    x_min = (COURT_WIDTH - width) / 2.0
    x_max = x_min + width
    return (
        x_min - tol <= float(X) <= x_max + tol
        and 0.0 - tol <= float(Y) <= COURT_LENGTH + tol
    )


def court_to_canvas_xy(X: float, Y: float, scale: float, margin_px: int) -> Tuple[int, int]:
    # Far baseline is top (Y=0), near baseline is bottom (Y=COURT_LENGTH)
    px = int(round(float(margin_px) + float(X) * float(scale)))
    py = int(round(float(margin_px) + float(Y) * float(scale)))
    return px, py


def draw_court(scale: float = 10.0, margin_ratio: float = 0.10) -> Tuple[np.ndarray, int]:
    margin_px = int(round(max(COURT_WIDTH, COURT_LENGTH) * float(scale) * float(margin_ratio)))
    W = int(round(COURT_WIDTH * float(scale) + 2 * margin_px))
    H_img = int(round(COURT_LENGTH * float(scale) + 2 * margin_px))
    img = np.full((H_img, W, 3), 255, dtype=np.uint8)

    green = (0, 210, 0)
    gray = (150, 150, 150)
    lw = max(1, int(round(float(scale) / 16)))

    def pt(x, y):
        return court_to_canvas_xy(x, y, scale, margin_px)

    cv2.rectangle(img, pt(0, 0), pt(COURT_WIDTH, COURT_LENGTH), green, lw)
    cv2.line(img, pt(SINGLE_MARGIN, 0), pt(SINGLE_MARGIN, COURT_LENGTH), green, lw)
    cv2.line(img, pt(SINGLE_MARGIN + SINGLES_WIDTH, 0), pt(SINGLE_MARGIN + SINGLES_WIDTH, COURT_LENGTH), green, lw)
    cv2.line(img, pt(0, NET_Y), pt(COURT_WIDTH, NET_Y), gray, lw)

    far_service = NET_Y - SERVICE_FROM_NET
    near_service = NET_Y + SERVICE_FROM_NET
    cv2.line(img, pt(SINGLE_MARGIN, far_service), pt(SINGLE_MARGIN + SINGLES_WIDTH, far_service), green, lw)
    cv2.line(img, pt(SINGLE_MARGIN, near_service), pt(SINGLE_MARGIN + SINGLES_WIDTH, near_service), green, lw)
    cv2.line(img, pt(COURT_WIDTH / 2.0, far_service), pt(COURT_WIDTH / 2.0, near_service), green, lw)

    return img, margin_px


def side_color(side: str, in_bound: bool = True) -> Tuple[int, int, int]:
    if not in_bound:
        return (130, 130, 130)
    side = str(side).lower()
    if side == "near":
        return (0, 80, 255)
    if side == "far":
        return (255, 170, 0)
    return (0, 0, 255)


def project_all_landings(bounce_df: pd.DataFrame, H: np.ndarray) -> pd.DataFrame:
    rows = []
    for _, row in bounce_df.iterrows():
        projected = image_to_court_xy(row["x"], row["y"], H)
        if projected is None:
            continue
        X, Y = projected
        rows.append({
            "frame_idx": int(row["frame_idx"]),
            "landing_no": int(row["landing_no"]),
            "X": float(X),
            "Y": float(Y),
            "court_side": str(row.get("court_side", "unknown")),
            "in_bound": bool(is_in_bounds(X, Y, singles=True)),
            "score": float(row["score"]) if pd.notna(row.get("score", np.nan)) else np.nan,
        })
    if not rows:
        return pd.DataFrame(columns=["frame_idx", "landing_no", "X", "Y", "court_side", "in_bound", "score"])
    return pd.DataFrame(rows).sort_values("frame_idx").reset_index(drop=True)


def draw_landings_on_court(
    base_court: np.ndarray,
    landings: List[dict],
    scale: float,
    margin_px: int,
    current_frame_idx: int,
    show_index: bool = False,
) -> np.ndarray:
    court_img = base_court.copy()

    for hit in landings:
        px, py = court_to_canvas_xy(hit["X"], hit["Y"], scale, margin_px)
        in_bound = bool(hit.get("in_bound", True))
        color = side_color(hit.get("court_side", "unknown"), in_bound=in_bound)
        is_current = int(hit.get("frame_idx", -1)) == int(current_frame_idx)

        radius = 4 if is_current else 2
        cv2.circle(court_img, (px, py), radius, color, -1, cv2.LINE_AA)

        if is_current:
            cv2.circle(court_img, (px, py), radius + 6, (0, 0, 0), 1, cv2.LINE_AA)
            cv2.circle(court_img, (px, py), radius + 8, (255, 255, 255), 1, cv2.LINE_AA)

        if show_index:
            cv2.putText(
                court_img,
                str(int(hit.get("landing_no", 0))),
                (px + 5, py - 5),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.32,
                (30, 30, 30),
                1,
                cv2.LINE_AA,
            )

    return court_img


def get_video_fps(video_path: Path, fallback: float = 30.0) -> float:
    cap = cv2.VideoCapture(str(video_path))
    fps = cap.get(cv2.CAP_PROP_FPS)
    cap.release()
    if fps is None or fps <= 0 or not np.isfinite(fps):
        return float(fallback)
    return float(fps)


def get_frame_files(frames_dir: Path) -> List[Path]:
    frames_dir = Path(frames_dir)
    files = sorted(list(frames_dir.glob("*.jpg")) + list(frames_dir.glob("*.jpeg")) + list(frames_dir.glob("*.png")))
    return files


def _frame_iter_from_images(frame_files: List[Path]):
    for idx, fp in enumerate(frame_files):
        frame = cv2.imread(str(fp))
        if frame is None:
            continue
        yield idx, frame


def _frame_iter_from_video(video_path: Path):
    cap = cv2.VideoCapture(str(video_path))
    idx = -1
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        idx += 1
        yield idx, frame
    cap.release()


def make_overlay_bounce_landings(
    video_path: Path,
    frames_dir: Path,
    bounce_csv: Path,
    roi_json: Path,
    out_path: Path,
    court_scale: float = 10.0,
    court_margin: float = 0.10,
    court_ratio: float = 0.35,
    bounce_coord_scale: float = 1.0,
    show_index: bool = False,
    source: str = "frames",
    fps: Optional[float] = None,
):
    video_path = Path(video_path)
    frames_dir = Path(frames_dir)
    bounce_csv = Path(bounce_csv)
    roi_json = Path(roi_json)
    out_path = Path(out_path)

    bounce_df = load_bounce_events(bounce_csv, coord_scale=bounce_coord_scale)
    H = load_homography_from_roi(roi_json)
    landing_df = project_all_landings(bounce_df, H)

    print(f"[INFO] loaded bounce events: {len(bounce_df)}")
    print(f"[INFO] projected landings: {len(landing_df)}")

    landing_by_frame: Dict[int, pd.DataFrame] = {
        int(frame_idx): sub.copy() for frame_idx, sub in landing_df.groupby("frame_idx")
    }

    if fps is None or fps <= 0:
        fps = get_video_fps(video_path, fallback=30.0) if video_path.exists() else 30.0

    # Important: bounce.py uses dataset/<video>/frames frame_idx.
    # Therefore the default video source must be the extracted frame sequence,
    # not cv2.VideoCapture(raw_video), because VideoCapture can decode/drop frames
    # differently and create progressive drift.
    frame_files = get_frame_files(frames_dir)
    use_frames = source == "frames"
    if use_frames:
        if not frame_files:
            raise FileNotFoundError(f"No extracted frames found in {frames_dir}. Use --source video only for debugging.")
        first = cv2.imread(str(frame_files[0]))
        if first is None:
            raise ValueError(f"Cannot read first frame: {frame_files[0]}")
        H_img, W = first.shape[:2]
        frame_iter = _frame_iter_from_images(frame_files)
        total_frames = len(frame_files)
        print(f"[INFO] source=frames, frame_count={total_frames}, fps={fps:.3f}")
    else:
        if not video_path.exists():
            raise FileNotFoundError(f"video_path not found: {video_path}")
        cap_probe = cv2.VideoCapture(str(video_path))
        W = int(cap_probe.get(cv2.CAP_PROP_FRAME_WIDTH))
        H_img = int(cap_probe.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap_probe.get(cv2.CAP_PROP_FRAME_COUNT))
        cap_probe.release()
        if W <= 0 or H_img <= 0:
            raise ValueError(f"Cannot read video dimensions: {video_path}")
        frame_iter = _frame_iter_from_video(video_path)
        print(f"[WARN] source=video. If sync drifts, use default source=frames.")
        print(f"[INFO] source=video, frame_count={total_frames}, fps={fps:.3f}")

    if not landing_df.empty:
        max_bounce_frame = int(landing_df["frame_idx"].max())
        if max_bounce_frame >= total_frames:
            print(
                f"[WARN] max bounce frame {max_bounce_frame} >= source frame count {total_frames}. "
                "Check whether bounce.py and visualization.py are using the same extracted frames."
            )

    court_w = int(round(W * float(court_ratio)))
    total_w = W + court_w

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out = cv2.VideoWriter(str(out_path), fourcc, float(fps), (total_w, H_img))
    if not out.isOpened():
        raise RuntimeError(f"Cannot open VideoWriter: {out_path}")

    base_court, margin_px = draw_court(scale=court_scale, margin_ratio=court_margin)
    accumulated_landings: List[dict] = []

    for frame_idx, frame in tqdm(frame_iter, total=total_frames):
        current = landing_by_frame.get(frame_idx)
        if current is not None and not current.empty:
            for _, row in current.iterrows():
                accumulated_landings.append(row.to_dict())

        court_img = draw_landings_on_court(
            base_court=base_court,
            landings=accumulated_landings,
            scale=court_scale,
            margin_px=margin_px,
            current_frame_idx=frame_idx,
            show_index=show_index,
        )
        court_resized = cv2.resize(court_img, (court_w, H_img), interpolation=cv2.INTER_AREA)

        combined = np.zeros((H_img, total_w, 3), dtype=np.uint8)
        combined[:, :W] = frame
        combined[:, W:] = court_resized
        out.write(combined)

    out.release()
    print(f"[DONE] overlay saved -> {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Create a clean video with only synchronized bounce landings on a side court."
    )
    parser.add_argument("video_path", type=str, help="例如 raw_videos/testVid.mp4")
    parser.add_argument("--frames-dir", type=str, default=None, help="預設讀 dataset/<video>/frames，與 bounce.py 的 frame_idx 對齊")
    parser.add_argument("--bounce-csv", type=str, default=None, help="預設讀 dataset/<video>/bounce_detector/bounce_events.csv")
    parser.add_argument("--roi-json", type=str, default=None, help="預設讀 dataset/<video>/roi_config.json")
    parser.add_argument("--out-overlay", type=str, default=None, help="輸出影片路徑")
    parser.add_argument("--bounce-coord-scale", type=float, default=1.0, help="若 bounce.py 用 --scale 0.5 跑，這裡填 2.0")
    parser.add_argument("--court-scale", type=float, default=10.0)
    parser.add_argument("--court-margin", type=float, default=0.10)
    parser.add_argument("--court-ratio", type=float, default=0.35)
    parser.add_argument("--show-index", action="store_true", help="在右側落點旁顯示序號")
    parser.add_argument("--source", choices=["frames", "video"], default="frames", help="預設 frames，才能跟 bounce_events.csv 的 frame_idx 完全同步")
    parser.add_argument("--fps", type=float, default=None, help="輸出 FPS；預設讀原影片 FPS")
    args = parser.parse_args()

    set_video_path(Path(args.video_path))

    make_overlay_bounce_landings(
        video_path=Path(args.video_path),
        frames_dir=Path(args.frames_dir) if args.frames_dir else FRAMES_DIR,
        bounce_csv=Path(args.bounce_csv) if args.bounce_csv else BOUNCE_EVENTS_CSV,
        roi_json=Path(args.roi_json) if args.roi_json else ROI_JSON,
        out_path=Path(args.out_overlay) if args.out_overlay else OUT_PATH_OVERLAY,
        court_scale=args.court_scale,
        court_margin=args.court_margin,
        court_ratio=args.court_ratio,
        bounce_coord_scale=args.bounce_coord_scale,
        show_index=args.show_index,
        source=args.source,
        fps=args.fps,
    )


if __name__ == "__main__":
    main()
